### PR TITLE
fix(CheckboxE): Fix unchecked disabled styles and Firefox border glitch 

### LINKED ISSUE #3007: RadioE and CheckboxE in Firefox have strange sheered rendering
Screenshot 2022-01-21 at 11 35 56
Screenshot 2022-01-21 at 11 36 48

### PR DESCRIPTION
**Pull request by jpveooys**
## Related issue

Resolves #3007

## Overview

This:

- refactors the CheckboxE StyledCheckbox styles
- fixes a glitch with the active and hover borders in Firefox
- fixes styling for a disabled, unchecked checkbox

## Link to preview

- [Storybook](https://5e25c277526d380020b5e418-bokayohatk.chromatic.com/?path=/docs/checkbox-experimental--default)
- [Non-Storybook](https://red-playground.netlify.app/)

## Reason

To fix rendering in Firefox and make the disabled state worth as expected.

## Work carried out

- [x] Refactor styles
- [x] Fix glitch with active and hover border in Firefox
- [x] Fix unchecked disabled styling and add stories

#### Before

image

#### After

image

#### Before

image

#### After

image

## Developer notes

Note: Would suggest using the browser zoom to test in Firefox over the Storybook zoom (Storybook uses a transform which causes box-shadow artefacts in Firefox).

### CODE REVIEW

File: packages/react-component-library/src/components/CheckboxE/partials/StyledCheckmark.tsx [hunk 1]
```diff
@@ -14,9 +17,46 @@ export const StyledCheckmark = styled.div`
...
+  }
+
   &::after {
     content: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICA8cGF0aCBkPSJNMCAwaDI0djI0SDB6IiBmaWxsPSJub25lIiAvPgogICAgPHBhdGggdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMywgNCkiIGQ9Ik04LjgyMiAwYzEuMDUtLjAyNyAxLjU3NCAxLjMwNC44MjcgMi4wOEw0LjI5OCA3Ljc0YS44My44MyAwIDAgMS0xLjIwNyAwTC4zNzYgNC44NTVDLS43NTIgMy43MTguOTE0IDEuOTU2IDEuOTkgMy4xNDlsMS41MDggMS41OTVjLjEwNS4xMS4yODguMTEuNDA3IDBsNC4xMy00LjM3QTEuMSAxLjEgMCAwIDEgOC44MjMgMHoiCiAgICAgICAgICBmaWxsPSIjRkZGIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==);
+    display: none;
     border-radius: 2px;
     color: ${color('neutral', 'white')};
   }
+
+  ${StyledCheckbox}:hover, ${StyledCheckbox}:active {
```
Comment (jpveooys) [inline packages/react-component-library/src/components/CheckboxE/partials/StyledCheckmark.tsx:33]: Previously the `StyledCheckbox` styled were spread across three files (which was hard to follow, and they contained some contradictions).

I used this pattern to move them all into this file (using a parent element as a selector):

https://styled-components.com/docs/advanced#referring-to-other-components

File: packages/react-component-library/src/components/CheckboxE/partials/StyledCheckmark.tsx [hunk 2]
```diff
@@ -14,9 +17,46 @@ export const StyledCheckmark = styled.div`
...
+  }
+
   &::after {
     content: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICA8cGF0aCBkPSJNMCAwaDI0djI0SDB6IiBmaWxsPSJub25lIiAvPgogICAgPHBhdGggdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMywgNCkiIGQ9Ik04LjgyMiAwYzEuMDUtLjAyNyAxLjU3NCAxLjMwNC44MjcgMi4wOEw0LjI5OCA3Ljc0YS44My44MyAwIDAgMS0xLjIwNyAwTC4zNzYgNC44NTVDLS43NTIgMy43MTguOTE0IDEuOTU2IDEuOTkgMy4xNDlsMS41MDggMS41OTVjLjEwNS4xMS4yODguMTEuNDA3IDBsNC4xMy00LjM3QTEuMSAxLjEgMCAwIDEgOC44MjMgMHoiCiAgICAgICAgICBmaWxsPSIjRkZGIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==);
+    display: none;
     border-radius: 2px;
     color: ${color('neutral', 'white')};
   }
+
+  ${StyledCheckbox}:hover &, ${StyledCheckbox}:active & {
```
Comment (jpveooys) [inline packages/react-component-library/src/components/CheckboxE/partials/StyledCheckmark.tsx:33]: Previously the `StyledCheckbox` styled were spread across three files (which was hard to follow, and they contained some contradictions).

I used this pattern to move them all into this file (using a parent element followed by `&` as a selector):

https://styled-components.com/docs/advanced#referring-to-other-components

**Review by m7kvqbe1 — APPROVED** [review]
LGTM

**Comment by k9dh3zij** [comment]
👍 Thank you!
