### PR TITLE
fix(Timeline): Correct row column background mismatch

### LINKED ISSUE #1656: Fix alternating / checkerboard Timeline column backgrounds

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related issue

Closes #1656

## Overview

Correct row column background mismatch.

## Reason

>The background colours for the row and header columns were not matched.

## Work carried out

- [x] Adjust ternary logic in styled-component

## Screenshot

Screenshot 2020-11-13 at 12 08 58

### CODE REVIEW

File: packages/react-component-library/src/components/Timeline/TimelineRows.tsx [hunk 1]
```diff
@@ -61,7 +61,7 @@ const StyledTimelineRowWeek = styled.div<StyledTimelineRowWeekProps>`
   display: inline-block;
   height: 100vh;
   background-color: ${({ isOddNumber }) =>
-    isOddNumber ? TIMELINE_BG_COLOR : TIMELINE_ALT_BG_COLOR};
+    isOddNumber ?  TIMELINE_ALT_BG_COLOR : TIMELINE_BG_COLOR};
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/Timeline/TimelineRows.tsx:64]: 🤣

**Review by thyhjwb6 — APPROVED** [review]
👍
