### PR TITLE
fix(Badge): Add ability to drill arbitrary props

### LINKED ISSUE #1121: Badge Component - data-testid attribute ignored
### Steps to reproduce
`<Badge data-testid="badge-testid">1</Badge>
`

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related issue

Closes #1121

## Overview

Make Badge apply additional arbitrary props to component wrapper element.

## Reason

> Downstream consumers want to be able to apply their own test IDs to the components.

## Work carried out

- [x] Add ability to drill additional arbitrary props
- [x] Add automated test

### CODE REVIEW

File: packages/react-component-library/src/components/Badge/Badge.tsx [hunk 1]
```diff
@@ -49,7 +50,7 @@ export const Badge: React.FC<BadgeProps> = ({
   )
 
   return (
-    <span className={classes} data-testid="badge">
+    <span className={classes} {...rest} data-testid="badge">
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/Badge/Badge.tsx]: Should `{...rest}` be last so consumers can potentially override `data-testid` too?

**Review by thyhjwb6 — COMMENTED** [review]
A small comment about overriding `data-testid` because doing it in this order means it definitely cannot be.

File: packages/react-component-library/src/components/Badge/Badge.tsx (hunk 1 above)
Comment (m7kvqbe1) [reply packages/react-component-library/src/components/Badge/Badge.tsx]: I'll move it around but I don't think it would make a difference because Babel strips it.

Comment (thyhjwb6) [reply packages/react-component-library/src/components/Badge/Badge.tsx]: Yes! I just remembered that too..

**Review by thyhjwb6 — APPROVED** [review]
👍
