### PR TITLE
fix(Select): Handle overflowing option label

### LINKED ISSUE #2951: Select / drop-down overflow bug
When a select element contains text that does not fit it overflows the component, blocking the "X" and drop down icon.

I'm not sure how you would want to fix, but some kind of truncation and tooltip combination could work.

bug
.

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related issue

Closes #2951

## Overview

Truncate and add ellipses to overflowing select label content. Also add Tooltip to the selected option label that displays on hover.

## Link to preview

https://61f2771ee6b8899f7e9c826a--infallible-meitner-a1d8bb.netlify.app

## Reason

>When a select element contains text that does not fit it overflows the component, blocking the "X" and drop down icon.

## Work carried out

- [x] Remove some unsued imports
- [x] Handle overflowing selected values
- [x] Check optional onChange callback exists before invoking to avoid error

## Developer notes

This component is about to be superseeded by the new `3.x.x` implementation. I've created a [seperate issue](https://github.com/defencedigital/mod-uk-design-system/issues/3023) to look into the behaviour there as it doesn't appear to handle this scenario yet.

### CODE REVIEW

File: packages/react-component-library/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -61,12 +61,14 @@ export const Select: React.FC<SelectProps> = ({
       option && option.value !== undefined ? option.value : null
     setSelectedValue(selectedValue)
 
-    onChange({
-      target: {
-        name,
-        value: selectedValue,
-      },
-    })
+    if (onChange) {
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/Select/Select.tsx:64]: I wonder if it's worth adding a test to cover this.

**Review by thyhjwb6 — APPROVED** [review]
👍

File: packages/react-component-library/src/components/Select/Select.test.tsx [hunk 2]
```diff
@@ -333,4 +333,33 @@ describe('Select', () => {
       })
     })
   })
+
+  describe('when the optional `onChange` callback is not provided and the user selects an items', () => {
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/Select/Select.test.tsx]: Minor typo here

File: packages/react-component-library/src/components/Select/Select.test.tsx [hunk 3]
```diff
@@ -333,4 +333,33 @@ describe('Select', () => {
...
+      const input = wrapper.getByTestId('react-select-vendor-input')
+      fireEvent.focus(input)
+      fireEvent.keyDown(input, {
+        key: 'ArrowDown',
+        code: 40,
+      })
+    })
+
+    it('should not attempt to invoke the `onChange` callback', () => {
+      expect(() => userEvent.click(wrapper.getByText('Foo'))).not.toThrow(
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/Select/Select.test.tsx]: I am wondering if checking the message is quite specific and just having `.not.toThrow()` is enough but actually it just works as it is so up to you.

**Review by thyhjwb6 — APPROVED** [review]
👍

**Comment by k9dh3zij** [comment]
Thanks @m7kvqbe1 just a small bug I noticed if the mouse comes from below the component (may be related to where the tooltip is?):

https://user-images.githubusercontent.com/73531035/151334205-3b5e9e63-6722-415e-90db-c9287563264c.mov

**Comment by m7kvqbe1** [comment]
@k9dh3zij That issue should now be resolved - the fix also in turn resolves a related positioning and z-index issue:

Screenshot 2022-01-27 at 10 33 47
Screenshot 2022-01-27 at 10 39 44

**Comment by k9dh3zij** [comment]
Great, thanks @m7kvqbe1 ! 👍
