### PR TITLE
fix(Timeline): Render events beyond range

### LINKED ISSUE #1510: TimelineEvent not overrunning between months as expected
### Steps to reproduce
 I have come across one issue in `Timeline` component. 
**Given** a `Timeline` is displaying one month window
**When** there is a `TimelineEvent` block in it which is running over that month, 
**Then** expected to see those extra days in the following month when navigated to it, 

**Instead**, it is displaying everything in the same window(month) by running over that month in the `Timeline` calendar.  Please see the attached screenshots and steps to replicate.

1. *Using **2.15.0** version*
"@royalnavy/css-framework": **"2.15.0",**
    "@royalnavy/eslint-config-react": **"2.15.0",**
    "@royalnavy/fonts": **"2.15.0",**
    "@royalnavy/icon-library": **"2.15.0",**
    "@royalnavy/react-component-library": **"2.15.0",**

2. *Timeline in code*
timelineInCode
`return (
    <Timeline
      startDate={new Date(2020, 3, 1)}
      today={new Date(2020, 3, 15)}
      range={1}
      hasSide>
      <TimelineTodayMarker />
      <TimelineMonths />
      <TimelineWeeks />
      <TimelineDays />
      <TimelineRows>
        <TimelineRow name="Row 1">
          <TimelineEvents>
            <TimelineEvent
              startDate={new Date(2020, 3, 14)}
              endDate={new Date(2020, 4, 8)}
            >
              Event 1
            </TimelineEvent>
          </TimelineEvents>
        </TimelineRow>
        <TimelineRow name="Row 2">
          <TimelineEvents>
            <TimelineEvent
              startDate={new Date(2020, 3, 13)}
              endDate={new Date(2020, 3, 28)}
            >
              Event 2
            </TimelineEvent>
          </TimelineEvents>
        </TimelineRow>
      </TimelineRows>
    </Timeline>
  )
`

3. *Step 3*
### Screenshot
* First month on Timline window
blockOverFlowFirstMonth

* Second month on Timline window
emptyMonthTwo

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related issue

Closes #1510 

## Overview

Render events beyond displayed ranges and add chevrons to denote start and end.

## Reason

Events that started or ended outside of the displayed range would not render.

## Work carried out

- [x] Enhance `useTimelinePosition` hook
- [x] Add visual cue to default `TimelineEvent` presentation
- [x] Add automated tests
- [x] Mark `isBeforeStart` and `isAfterEnd` as deprecated
- [x] Update documentation

## Screenshot

Screenshot 2020-10-21 at 14 05 37

### CODE REVIEW

**Comment by m7kvqbe1** [comment]
I'm considering testing the `useTimelinePosition` hook independently as it is exposed to consumers.

File: packages/react-component-library/src/components/Timeline/TimelineEvent.tsx [hunk 1]
```diff
@@ -18,7 +18,8 @@ export interface TimelineEventWithRenderContentProps
     endDate: Date,
     startDate: Date,
     widthPx: string,
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/Timeline/TimelineEvent.tsx:20]: Thinking about the parameters here for a major upgrade, we have the possibility of introducing a prop bag but maybe there is also a `positioning` `object` which includes `width`, `offset` and `maxWidth`.

File: packages/react-component-library/src/components/Timeline/TimelineEvent.tsx [hunk 2]
```diff
@@ -75,26 +134,35 @@ function renderDefault({
   offsetPx,
   startDate,
   widthPx,
+  maxWidthPx,
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/Timeline/TimelineEvent.tsx:137]: See previous point about considering a `positioning` `object`.

File: packages/react-component-library/src/components/Timeline/TimelineEvent.tsx [hunk 3]
```diff
@@ -118,15 +186,27 @@ export const TimelineEvent: React.FC<TimelineEventProps> = ({
   const {
     offset: offsetPx,
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/Timeline/TimelineEvent.tsx]: These renamed properties could be below the ones that do not need renaming on lines 190-193. This would be consistent with other areas of the code.

I always accepted this as a coding standard. Maybe we need a lint rule if we agree on this?

File: packages/react-component-library/src/components/Timeline/hooks/useTimelinePosition.ts [hunk 4]
```diff
@@ -47,19 +52,34 @@ export function useTimelinePosition(
...
-    width,
-    offset,
-    isBeforeStart,
-    isAfterEnd,
+    width: formatPx(options.dayWidth, width),
+    offset: formatPx(options.dayWidth, offset),
+    maxWidth: formatPx(options.dayWidth, maxWidth),
+    isBeforeStart: startsBeforeStart,
+    isAfterEnd: startsAfterEnd,
+    startsBeforeStart,
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/Timeline/hooks/useTimelinePosition.ts:78]: Let's have a quick chat about the fields that are not renamed at the top.

**Review by thyhjwb6 — COMMENTED** [review]
Looks great, a few comments for discussion. 👍

File: packages/react-component-library/src/components/Timeline/TimelineEvent.tsx (hunk 1 above)
Comment (m7kvqbe1) [reply packages/react-component-library/src/components/Timeline/TimelineEvent.tsx:20]: A ticket has been created to address this as part of the next major: https://github.com/Royal-Navy/design-system/issues/1592

**Review by thyhjwb6 — APPROVED** [review]
👍
