### PR TITLE
Fix `Timeline` start date update from side effect

### LINKED ISSUE #2470: Timeline component updates  if the props StartDate is changed
### Description
At the moment the startDate has has an effect when it is set on the initial render. Would it be possible that the timeline updates when the startDate props has changed?

### PR DESCRIPTION
**Pull request by thyhjwb6**
## Related issue
Closes #2470 

## Overview
It is possible that `startDate` is updated as a side effect and therefore the `Timeline` needs to update. This change dispatches an event which is handled by the reducer.

## Work carried out
- [x] Tidy up existing code
- [x] Handle `startDate`

### CODE REVIEW

**Review by jpveooys — COMMENTED** [review]
Looks OK to me :+1: 

But, it does something to the 'By fixed dates' story when navigating back a month:

fixed-dates

(It starts navigating back by longer and longer periods of times...)

Navigating back and forward doesn't make too much sense when using fixed dates but might be worth checking why the behaviour's changed (especially as it is in Storybook).

**Comment by thyhjwb6** [comment]
> But, it does something to the 'By fixed dates' story when navigating back a month:

Nice spot! Fix and supporting test added

File: packages/react-component-library/src/components/Timeline/context/index.tsx [hunk 1]
```diff
@@ -24,6 +29,23 @@ export const TimelineProvider: React.FC<TimelineProviderProps> = ({
...
+      {
+        ...options,
+        endDate: state.getNewEndDate(),
+        hoursBlockSize: state.currentScaleOption.hoursBlockSize,
+      },
+      state.width
+    )
+
+    dispatch({ scaleOptions, type: TIMELINE_ACTIONS.CHANGE_START_DATE })
+  }, [options.startDate])
```
Comment (jpveooys) [inline packages/react-component-library/src/components/Timeline/context/index.tsx:47]: Strictly speaking, the `useEffect()` hook call is missing dependencies on `options` and `state`. This will get picked up once #2454 is in.

I think most likely we'd need to use [`usePrevious`](https://reactjs.org/docs/hooks-faq.html#how-to-get-the-previous-props-or-state) to check if the startDate has actually changed (as with the other hook dependencies in you won't know which one has changed). But happy to leave that to #2454 as there are probably other instances of the same thing about.

**Review by jpveooys — APPROVED** [review]

File: packages/react-component-library/src/components/Timeline/context/index.tsx (hunk 1 above)
Comment (thyhjwb6) [reply packages/react-component-library/src/components/Timeline/context/index.tsx:47]: 💯  having investigated #2454 it is a larger piece of work which we should look at holistically.
