### PR TITLE
Fix NumberInput with unit and user keyboard input

### LINKED ISSUE #1458: Number input with trailing Unit usability
When the number input has a trailing unit, some strange behaviours emerge:

To replicate:
- Fill the number input with a value
- move your cursor to the left of the `m3`
- If your cursor is after the space directly before `m3`, it bumps the cursor to the end and doesn't edit the number

Editing the number sometimes also produces strange behaviour (e.g. the number not being deleted/can't update)

### PR DESCRIPTION
**Pull request by thyhjwb6**
## Related issue
Fixes #1458 

## Overview
Separates out the `unit` from the `input` `value` as this was causing a range of issues.

## Reason
User is not able to edit value as expected.

## Work carried out
- [x] Fix issues
- [x] Refactor existing code to simplify

## Screenshot
number-input

## Notes
- A separate ticket #1526 has been raised to convert the component to use Styled Components

### CODE REVIEW

File: packages/react-component-library/src/components/NumberInput/NumberInput.tsx [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import React, { FormEvent } from 'react'
+import React from 'react'
 import classNames from 'classnames'
 import { isFinite, isNil, without } from 'lodash'
```
Comment (m7kvqbe1) [inline packages/react-component-library/src/components/NumberInput/NumberInput.tsx]: Looks like `without` is an unused import.

File: packages/react-component-library/src/components/NumberInput/useInputText.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
+import { useEffect, useRef, useState } from 'react'
+import { isFinite } from 'lodash'
+
+import { UnitPosition } from './NumberInput'
+import { UNIT_POSITION } from './constants'
+
+const EXTRA_SPACING = 3
+
+function getTextWidth({
```
Comment (m7kvqbe1) [inline packages/react-component-library/src/components/NumberInput/useInputText.ts:9]: Clever technique! I assume it plays nice cross browser?

**Review by m7kvqbe1 — COMMENTED** [review]
Quite a bit of complexity but I think the solution is nice.

I tried hard to break it and couldn't - user experience is really nice now.

File: packages/react-component-library/src/components/NumberInput/useInputText.ts (hunk 2 above)
Comment (thyhjwb6) [reply packages/react-component-library/src/components/NumberInput/useInputText.ts:9]: This is IE 11..

number-input-ie11

**Review by m7kvqbe1 — APPROVED** [review]
