### PR TITLE
fix(RadioE): Fix disabled styling and Firefox border glitch

### LINKED ISSUE #3052: RadioE disabled styling is incorrect
Currently there is only an unchecked disabled state which looks like this:

image

The checked disabled state is currently missing.

The disabled states should instead look like this:

image

### PR DESCRIPTION
**Pull request by jpveooys**
## Related issue

#3007
Resolves #3052 

## Overview

This:

- fixes a glitch with the hover and checked border in Firefox
- adjusts the size of that border to 2px
- corrects the disabled styles for both checked and unchecked states

## Link to preview

- [Storybook](https://5e25c277526d380020b5e418-jrrxzijbql.chromatic.com/?path=/docs/radio-experimental--default)
- [Non-Storybook](https://red-playground.netlify.app/)

## Reason

Make the component better and make the component line up with the design spec.

## Work carried out

- [x] Rework hover/checked border
- [x] Correct various disabled styles
- [x] Update stories

### Checked

<details>
<summary>Before and after animation</summary>

checked

</details>

<details>
<summary>Firefox, before</summary>

checked-firefox-before

</details>

<details>
<summary>Firefox, after</summary>

checked-firefox-after

</details>

#### Before

disabled-before

#### After

Screenshot 2022-02-02 at 16-50-53 Radio (Experimental) - Disabled ⋅ Storybook

#### Before

disabled-checked-before

#### After

disabled-checked-after

## Developer notes

Note: I'd recommend using the browser zoom instead of the Storybook zoom in Firefox to check this – Storybook uses a `transform` to zoom and it seems this causes glitches with a round box-shadow in Firefox.

The original Firefox glitch in the issue was due to half the border being a border and the other half being a box-shadow.

One follow-up issue has been created:

- #3056

The same Firefox glitch for CheckboxE will be resolved in a separate PR.

### CODE REVIEW

File: packages/react-component-library/src/components/RadioE/partials/StyledRadio.tsx [hunk 1]
```diff
@@ -10,17 +10,33 @@ interface StyledRadioProps {
   $isChecked?: boolean
 }
 
-const RADIO_FOCUS_WIDTH = '0.1rem'
+const RADIO_ACTIVE_BORDER_WIDTH = '2px'
 
 const { spacing, fontSize, color, animation } = selectors
 
+const BackgroundColour = css<StyledRadioProps>`
```
Comment (jpveooys) [inline packages/react-component-library/src/components/RadioE/partials/StyledRadio.tsx]: Was getting a bit repetitive and confusing following the `$isDisabled` overrides, so I've used a slightly different approach here.

File: packages/react-component-library/src/components/RadioE/partials/StyledRadio.tsx [hunk 2]
```diff
@@ -10,17 +10,33 @@ interface StyledRadioProps {
...
+  ${({ $isDisabled }) =>
+    $isDisabled ? color('neutral', '200') : color('action', '500')}
+`
+
+const CheckmarkCheckedFillColour = css<StyledRadioProps>`
+  ${({ $isDisabled }) =>
+    $isDisabled ? color('neutral', '200') : color('action', '500')}
+`
+
 export const StyledRadio = styled.div<StyledRadioProps>`
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/RadioE/partials/StyledRadio.tsx:32]: I know that this was already quite long but I do think it's a tricky maintenance point as it's effectively a function with nearly 100 lines and there are comments which sets alarm bells that it could be broken up.

**Review by thyhjwb6 — APPROVED** [review]
The end result looks good. I wonder if the styled component could be refactored but it's not a blocker.

👍

File: packages/react-component-library/src/components/RadioE/partials/StyledRadio.tsx (hunk 2 above)
Comment (jpveooys) [reply packages/react-component-library/src/components/RadioE/partials/StyledRadio.tsx:32]: Yeah, definitely. It will need refactoring to fix #3056 so I'll add a comment to that issue

**Comment by k9dh3zij** [comment]
👍  Thanks @jpveooys  looks good on Chrome! Thanks for spotting the background colour issue too! :)
