### PR TITLE
fix(Radio): Resolve incorrect active container background color

### LINKED ISSUE #3056: Wrong background colour for RadioE selected state
https://storybook.design-system.digital.mod.uk/?path=/docs/radio-experimental--default

Selected background colour should be Action 000

image

### LINKED ISSUE #3135: Abstract and consolidate Checkbox / Radio styling
These components are visually very similar but they each have their own sets of styles.

The code for these styles appears to have diverged quite radically.

It would be good to abstract and consolidate these styles.

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related issue

Closes #3056 
Closes #3135

## Overview

Refactor and resolve incorrect `Radio` component container variant active state styling.

## Link to preview

https://62275b4f39eb3d0cb221031d--admiring-allen-740480.netlify.app

## Reason

>Needs to be styled in line with spec and to match `Checkbox`.

## Work carried out

- [x] Supplement automated tests
- [x] Refactor Checkbox and Radio implementations
- [x] Resolve styling
- [x] Handle implicit deselection of radio within collection

### CODE REVIEW

**Review by jpveooys — COMMENTED** [review]
Seems to be a problem with the radio groups in the example stories (my screen recorder isn't working at the moment :disappointed: ):

After selecting the first then second radio:

image

And then repeating:

image

**Comment by jpveooys** [comment]
@m7kvqbe1 FYI there's a type error in the smoke test...

File: packages/react-component-library/src/components/CheckboxRadioBase/CheckboxRadioBaseProps.ts [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+   */
+  variant?: CheckboxRadioVariantType
+  /**
+   * HTML `type` attribute associated with the input (Checkbox or Radio).
+   */
+  type: 'checkbox' | 'radio'
+  /**
+   * Custom implementations of presentational styled-components.
+   */
+  partials: Record<'root' | 'checkmark', React.ReactElement>
```
Comment (jpveooys) [inline packages/react-component-library/src/components/CheckboxRadioBase/CheckboxRadioBaseProps.ts]: Are we able to pass the components themselves through (as `React.ComponentType`) so we don't need to use `React.cloneElement`?

File: packages/react-component-library/src/components/CheckboxRadioBase/CheckboxRadioBase.tsx [hunk 2]
```diff
@@ -0,0 +1,144 @@
...
+
+    const handleKeyUp = (_: React.KeyboardEvent) => {
+      localRef.current?.focus()
+    }
+
+    const handleOnChange = (e: React.FormEvent<HTMLInputElement>) => {
+      setIsChecked(!isChecked)
+
+      if (type === 'radio') {
+        const event = new CustomEvent('_radio:selected', {
```
Comment (jpveooys) [inline packages/react-component-library/src/components/CheckboxRadioBase/CheckboxRadioBase.tsx]: Would be good to include some vendor namespace I think – e.g. `_mod-uk-ds:radio:selected`

File: packages/react-component-library/src/components/CheckboxRadioBase/CheckboxRadioBase.tsx [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+        const isDifferent = emittedRef !== localRef
+        const isInCollection = emittedRef.current.attributes.name.value === name
+        const isRadio = type === 'radio'
+
+        if (isDifferent && isInCollection && isRadio) {
+          setIsChecked(false)
+        }
+      }
+
+      document.addEventListener('_radio:selected', handleSelected)
```
Comment (jpveooys) [inline packages/react-component-library/src/components/CheckboxRadioBase/CheckboxRadioBase.tsx]: Just a note for reference really, I think `document.addEventListener('change', handleSelected, {capture: true})` could've been made to work too with some checks on the target (but the custom event works fine so let's stick with that).

**Review by jpveooys — COMMENTED** [review]
Nice work! Couple of other comments above.

**Review by jpveooys — APPROVED** [review]
