### PR TITLE
fix(Timeline): Update scale index condition

### LINKED ISSUE #2765: Full-width timeline zooms out on viewport width increase
### Steps to reproduce

1. Go to https://storybook.design-system.digital.mod.uk/?path=/story/compound-timeline--full-width (canvas tab)
2. Decrease the viewport width
3. Zoom in the timeline fully
4. Increase the viewport width

The timeline resets to the month zoom level.

### Demo

timeline-zoom

### PR DESCRIPTION
**Pull request by thyhjwb6**
## Related issue
Closes #2765 

## Overview
There is a bug when zoomed all the way in and resizing the window.

It is possible for the scale index to be 0 which is falsy but we still want to satisfy the `true` side of the condition.

## Work carried out
- [x] Fix bug with test

### CODE REVIEW

File: packages/react-component-library/src/components/Timeline/context/reducer.ts [hunk 1]
```diff
@@ -105,9 +105,9 @@ export function reducer(
     case TIMELINE_ACTIONS.CHANGE_WIDTH:
     case TIMELINE_ACTIONS.INITIALISE: {
       const scaleOptions = buildScaleOptions(state.options, action.width)
-      const currentScaleIndex =
-        state.currentScaleIndex ||
-        scaleOptions.findIndex(({ isDefault }) => isDefault)
+      const currentScaleIndex = isNumber(state.currentScaleIndex)
+        ? state.currentScaleIndex
+        : scaleOptions.findIndex(({ isDefault }) => isDefault)
```
Comment (jpveooys) [inline packages/react-component-library/src/components/Timeline/context/reducer.ts]: Could consider:

```suggestion
      const currentScaleIndex = state.currentScaleIndex ?? scaleOptions.findIndex(({ isDefault }) => isDefault)
```

File: packages/react-component-library/src/components/Timeline/context/reducer.ts [hunk 2]
```diff
@@ -3,7 +3,7 @@ import {
   eachMonthOfInterval,
   eachWeekOfInterval,
 } from 'date-fns'
-import { padStart } from 'lodash'
+import { padStart, isNumber } from 'lodash'
```
Comment (jpveooys) [inline packages/react-component-library/src/components/Timeline/context/reducer.ts]: Would be nice to sort `isNumber` and `padStart`:

```suggestion
import { isNumber, padStart } from 'lodash'
```

File: packages/react-component-library/cypress/specs/timeline/index.spec.ts [hunk 3]
```diff
@@ -264,6 +264,18 @@ describe('Compound Timeline', () => {
         it('should fill the width', () => {
           cy.get(selectors.timeline.month).should('have.css', 'width', '1023px')
         })
+
+        describe('resize window', () => {
```
Comment (jpveooys) [inline packages/react-component-library/cypress/specs/timeline/index.spec.ts]: Would be good to make this consistent with the other `describe`s – perhaps something like:

```suggestion
        describe('resizing the window', () => {
```

**Review by jpveooys — APPROVED** [review]
Nice find :+1:
