### PR TITLE
fix(SidebarE): Add userLink and exitLink props

### LINKED ISSUE #1623: New Sidebar issues
1. 'View Profile' on the Sidebar User should be optional
2. Logout button on Sudebar User doesn't do anything/no option to pass prop yo do something
3. All content is pushed off the page, 'aside' should have absolute positioning and an increased z-index
4. Icons are no longer usableand 'graph' icon is missing from the library

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related issue

Closes #1623

## Overview

Add missing customisation to SidebarE component.

## Reason

> - 'View Profile' on the Sidebar User should be optional
> - Logout button on Sudebar User doesn't do anything/no option to pass prop yo do something

## Work carried out

- [x] Add additional props
- [x] Add automated tests
- [x] Update documentation

### CODE REVIEW

File: packages/react-component-library/src/components/TopLevelNavigation/SidebarE/SidebarUser.tsx [hunk 1]
```diff
@@ -61,12 +63,16 @@ const StyledSidebarUserText = styled.div`
     justify-content: center;
     flex-direction: column;
 
-    span:first-of-type {
+    a:hover {
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/TopLevelNavigation/SidebarE/SidebarUser.tsx:54]: Now that we know more about the patterns we want to adopt, could we consider refactoring this to use partials? Perhaps a separate ticket?

File: packages/react-component-library/src/components/TopLevelNavigation/SidebarE/SidebarUser.tsx [hunk 2]
```diff
@@ -141,33 +156,44 @@ export const SidebarUserE: React.FC<SidebarUserEProps> = ({
...
-      </StyledSidebarUser>
-    ),
-    'data-testid': `sidebar-user-${isOpen ? 'open' : 'closed'}`,
-  })
+  return (
+    <StyledSidebarUser
+      data-testid={`sidebar-user-${isOpen ? 'open' : 'closed'}`}
+    >
+      <StyledAvatar initials={initials} />
+      <Transition in={isOpen} timeout={TRANSITION_TIMEOUT} unmountOnExit>
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/TopLevelNavigation/SidebarE/SidebarUser.tsx:158]: This is getting hard to read now.

File: packages/react-component-library/src/components/TopLevelNavigation/SidebarE/Sidebar.test.tsx [hunk 3]
```diff
@@ -19,24 +24,22 @@ import {
...
-  />
-)
+const user = <SidebarUserE initials="HN" name="Horatio Nelson" />
 
 const userWithMenu = (
   <SidebarUserE
     initials="HN"
     name="Horatio Nelson"
-    link={<Link href="/user-profile">View profile</Link>}
+    userLink={<Link href="/user-profile">Profile</Link>}
```
Comment (thyhjwb6) [inline packages/react-component-library/src/components/TopLevelNavigation/SidebarE/Sidebar.test.tsx:27]: I am trying to understand why the consumer would compose the component with `userLink` and `exitLink` rather than just supplying everything as `children`.

**Review by thyhjwb6 — COMMENTED** [review]
This looks good. The main observation is the interface change for composing the user items/links.

File: packages/react-component-library/src/components/TopLevelNavigation/SidebarE/Sidebar.test.tsx (hunk 3 above)
Comment (m7kvqbe1) [reply packages/react-component-library/src/components/TopLevelNavigation/SidebarE/Sidebar.test.tsx:27]: The `children` allow the sub-menu (only available on in the collapsed sidebar state) to be populated with optional arbitrary menu items. We need a way differentiating the user and exit links from these.

When the sidebar is in an expanded state the `userLink` and `exitLink` are associated with an exit button and a 'View profile' link that has hardcoded text.

Maybe it doesn't make sense from a UX perspective to allow for the arbitrary children.

Screenshot 2020-11-20 at 13 01 13

Screenshot 2020-11-20 at 13 00 53

File: packages/react-component-library/src/components/TopLevelNavigation/SidebarE/SidebarUser.tsx (hunk 1 above)
Comment (m7kvqbe1) [reply packages/react-component-library/src/components/TopLevelNavigation/SidebarE/SidebarUser.tsx:54]: Yeah good shout - i'll break things out into a partials directory.

File: packages/react-component-library/src/components/TopLevelNavigation/SidebarE/Sidebar.test.tsx (hunk 3 above)
Comment (m7kvqbe1) [reply packages/react-component-library/src/components/TopLevelNavigation/SidebarE/Sidebar.test.tsx:27]: We have discussed this and decided to remove the optional arbitrary children for now.

**Review by thyhjwb6 — APPROVED** [review]
Looks good 👍 

Do we need to be concerned with this breaking anyone downstream?
