### PR TITLE
fix(Popover): Apply missing `aria-label` attribute

### LINKED ISSUE #3260: Accessibility fails when the  Popover is active
### Steps to reproduce
1. Go to the Popover Click to activate demo https://storybook.design-system.digital.mod.uk/?path=/story/popover--click-to-activate
2. Click the "Click on me" button
3. Click another story then go back on to unmount and remount the component.
https://storybook.design-system.digital.mod.uk/?path=/story/popover--click-to-activate
### Minimal reproduction
image

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related issue

Closes #3260

## Overview

Apply missing `aria-label` attribute to `Popover`.

## Reason

>Accessibility fails when the Popover is active.

## Work carried out

- [x] Supplement with automated tests
- [x] Add missing attribute and sensible default

### CODE REVIEW

File: packages/react-component-library/src/components/Popover/Popover.tsx [hunk 1]
```diff
@@ -41,6 +41,10 @@ export interface PopoverProps
    * Type of component to display (style varies accordingly).
    */
   scheme?: FloatingBoxSchemeType
+  /**
+   * Brief description of the Popover content to aid supportive technologies.
+   */
+  ariaLabel?: string
```
Comment (jpveooys) [inline packages/react-component-library/src/components/Popover/Popover.tsx]: Hmm `PopoverProps` is extending `FloatingBoxProps` which has explicit `aria-label` and `aria-labelledby` props. Should we avoid the prop duplication?

Comment (m7kvqbe1) [reply packages/react-component-library/src/components/Popover/Popover.tsx]: Nice spot!

**Review by jpveooys — APPROVED** [review]
